### ISSUE TITLE
coding idea

### ISSUE THREAD

**Issue by danik4985** [Darker-Ink/Darker-Ink#2]
> Hey, I'm DarkerInk. A Developer From Iowa. Give me some coding Ideas.

black people simulator xddd

**Comment by danik4985** [comment]
darkering respond!!!

**Comment by Darker-Ink** [comment]
> > Hey, I'm DarkerInk. A Developer From Iowa. Give me some coding Ideas.
> 
> black people simulator xddd

XD I haven't seen this (mostly since I haven't had internet) but I will totally keep this in mind :)

**Comment by danik4985** [comment]
omg can't wait
